name: Build Mac App

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: 获取代码
      uses: actions/checkout@v4

    - name: 安装 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安装 PyInstaller 打包工具
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: 开始生成 Mac 软件
      run: |
        pyinstaller --noconsole --onefile --windowed json_replacer.py

    - name: 上传打包好的成品供你下载
      uses: actions/upload-artifact@v4
      with:
        name: Mac-Version-App
        path: dist/
